#!/usr/bin/env php
<?php
// +----------------------------------------------------------------------
// | ThinkPHP [ WE CAN DO IT JUST THINK ]
// +----------------------------------------------------------------------
// | Copyright (c) 2006-2016 http://thinkphp.cn All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: yunwuxin <448901948@qq.com>
// +----------------------------------------------------------------------

define('APP_PATH', __DIR__ . '/../app/');
// 定义版本号
define('TPLAY_VERSION', '1.3.2');
//重定义扩展类库目录
define('EXTEND_PATH', __DIR__ . '/../simport/extend/');
//重定义第三方类库目录
define('VENDOR_PATH', __DIR__ . '/../simport/vendor/');
// 加载框架引导文件
require __DIR__ . '/../simport/thinkphp/start.php';
